# Generated by Django 5.1.2 on 2024-10-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CowinData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pincode", models.CharField(max_length=6)),
                ("fee_type", models.CharField(max_length=50)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_capacity", models.IntegerField()),
                ("available_capacity_dose1", models.IntegerField()),
                ("available_capacity_dose2", models.IntegerField()),
                ("min_age_limit", models.IntegerField()),
                ("vaccine", models.CharField(max_length=50)),
            ],
        ),
    ]
