name: Django CI with Virtual Environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure using Python 3.8

    - name: Create and activate virtual environment
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate  # Activate virtual environment
        python -m pip install --upgrade pip  # Upgrade pip inside virtual environment
        pip install -r requirements.txt  # Install dependencies inside virtual environment

    - name: Run database migrations  # Optional: Skip if no DB migrations needed
      run: |
        source venv/bin/activate  # Activate virtual environment
        python manage.py migrate  # Run migrations

    - name: Run Tests
      run: |
        source venv/bin/activate  # Activate virtual environment
        python manage.py test  # Run tests

    - name: Run Telegram Bot  # Optional: Running the bot, adjust this step as needed
      run: |
        source venv/bin/activate  # Activate virtual environment
        # python manage.py runserver
        nohup python myproject/manage.py run_bot &
