name: Deploy Telegram Bot

on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 */6 * * *'  # This cron expression runs every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure using Python 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot  # Install only your Telegram bot dependencies

    - name: Run bot for 6 hours
      run: |
        python bot.py &  # Replace with your actual bot script name
        sleep 21600  # Sleep for 6 hours (21600 seconds)
        pkill -f bot.py  # Kill the bot process after 6 hours
