name: Django Telegram Bot Workflow

on:
  push:
    branches:
      - main  # Change to your default branch if necessary
  pull_request:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest  # Change to your database if you're not using Postgres
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Change this to your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run database migrations
      env:
        DATABASE_URL: postgres://myuser:mypassword@localhost:5432/mydatabase  # Set your database URL
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        python manage.py test

    - name: Run the Telegram bot
      run: |
        nohup python manage.py start_telegram_bot &  # Consider using a service manager in production
